---
name: Labeler

on:
  workflow_dispatch:
  pull_request:
    branches:
      - $default-branch
  issues:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  labeler:
    uses: DevSecNinja/.github/.github/workflows/labeler.yml@8487f36bfcc8b040e5541937ba450411f6993e2b # v1.6.1
    permissions:
      contents: read
      pull-requests: write
      issues: write
