---
name: Labeler

on:
  workflow_dispatch:
  pull_request:
    branches:
      - $default-branch

permissions:
  contents: read

jobs:
  labeler:
    uses: DevSecNinja/.github/.github/workflows/labeler.yml@195660c2cde322b4f9402a20be4b2dac2fef77e0 # main
    permissions:
      contents: read
      pull-requests: write
