---
name: Label Sync

on:
  workflow_dispatch:
  push:
    branches:
      - $default-branch
    paths:
      - .github/labels.yaml
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  label-sync:
    uses: DevSecNinja/.github/.github/workflows/label-sync.yml@c1725a7573e1cb5277889d925901b477ee814352 # v1.7.0
    permissions:
      contents: read
      issues: write
