---
name: Labeler

on:
  workflow_dispatch:
  pull_request:
    branches:
      - $default-branch
  issues:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  labeler:
    uses: DevSecNinja/.github/.github/workflows/labeler.yml@c1725a7573e1cb5277889d925901b477ee814352 # v1.7.0
    permissions:
      contents: read
      pull-requests: write
      issues: write
