---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    uses: DevSecNinja/.github/.github/workflows/release.yml@195660c2cde322b4f9402a20be4b2dac2fef77e0 # main
    permissions:
      contents: write
    with:
      # renovate: datasource=github-releases depName=jdx/mise
      mise-version: "2026.4.5"
      tag: ${{ github.ref_name }}
