---
name: TODO to Issue

on:
  push:
    branches:
      - $default-branch

permissions:
  contents: read
  issues: write

jobs:
  run:
    uses: DevSecNinja/.github/.github/workflows/todo-to-issue.yml@7f2abdd838a855dba31a2b2de6358529fdcef09d # v1.8.0
    permissions:
      contents: read
      issues: write
    with:
      auto_assign: false
      label: "todo-to-issue"
