---
name: TODO to Issue

on:
  push:
    branches:
      - $default-branch

permissions:
  contents: read
  issues: write

jobs:
  run:
    uses: DevSecNinja/.github/.github/workflows/todo-to-issue.yml@195660c2cde322b4f9402a20be4b2dac2fef77e0 # main
    permissions:
      contents: read
      issues: write
