---
name: TODO to Issue

on:
  push:
    branches:
      - $default-branch

permissions:
  contents: read
  issues: write

jobs:
  run:
    uses: DevSecNinja/.github/.github/workflows/todo-to-issue.yml@c1725a7573e1cb5277889d925901b477ee814352 # v1.7.0
    permissions:
      contents: read
      issues: write
    with:
      auto_assign: false
      label: "todo-to-issue"
