---
name: Config Sync

on:
  push:
    branches:
      - main
    paths:
      - config-sync/files/**
      - .github/sync.yml
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

# checkov:skip=CKV_GHA_7: This workflow pushes config files, not build artifacts.
permissions:
  contents: read

jobs:
  sync:
    name: Sync config files
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Sync files to repositories
        uses: BetaHuhn/repo-file-sync-action@8b92be3375cf1d1b0cd579af488a9255572e4619 # v1.21.1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          CONFIG_PATH: .github/sync.yml
          COMMIT_PREFIX: "chore: "
          PR_LABELS: config-sync
          COMMIT_EACH_FILE: false
