---
name: Lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: DevSecNinja/.github/.github/workflows/lint.yml@60076760e7e1cb6a94d40def5ae7fac07c357153 # PR #66
    permissions:
      contents: read
      security-events: write
    with:
      # renovate: datasource=github-releases depName=jdx/mise
      mise-version: "2026.4.9"
      lint-config-dir: config-sync/files
