---
name: Lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    uses: DevSecNinja/.github/.github/workflows/lint.yml@4d799d366e6af6fd45ca2e7c4dfce6c12467fe09 # PR #66
    permissions:
      contents: read
      security-events: write
    with:
      # renovate: datasource=github-releases depName=jdx/mise
      mise-version: "2026.4.9"
